// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BallotSend struct {
	ID            int64              `json:"id"`
	ParticipantID int32              `json:"participant_id"`
	SongIds       []int32            `json:"song_ids"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
}

type PairwiseResult struct {
	ID        int64              `json:"id"`
	Winner    int32              `json:"winner"`
	Loser     int32              `json:"loser"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Participant struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	PhoneE164 string             `json:"phone_e164"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SmsInbound struct {
	ID            int64              `json:"id"`
	ParticipantID pgtype.Int4        `json:"participant_id"`
	Body          string             `json:"body"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
}

type Song struct {
	ID        int32              `json:"id"`
	Title     string             `json:"title"`
	YoutubeID string             `json:"youtube_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SongRating struct {
	SongID int32   `json:"song_id"`
	Rating float64 `json:"rating"`
	Rd     float64 `json:"rd"`
}
